name: Weekly Redeploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1" # Setiap Senin jam 09:00 WIB (UTC+7)

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Redeploy
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_PCxPtKEczFrbERVfQfZfzKI6O7F8/CqtHCIiMPf
